### ISSUE TITLE
Can it support C++ compiler？

### ISSUE THREAD

**Issue by chenluhong** [OpenNuvoton/NUC970_Linux_Applications#2]
hello，I know the project uses c compiler ，but if I want to use the C++ compiler？what should I do？

**Comment by chenluhong** [comment]
I just say the emwin project，thanks

**Comment by yachen** [comment]
Hi, arm-linux-gcc supports c++. Just remember to add -lstdc++ in your compiling option.

**Comment by chenluhong** [comment]
Thanks, at first I downloaded the code,  did a "make" to generate the "SimpleDemo",  then moved it to my testing board, but I found the touchscreen didn't work. I notice that there is "-lts" in Makefile, but I don't find libts.a or libts.so in tslib/ .

**Comment by yachen** [comment]
Please pull again. We just added tslib.a in 61bbce9. Thanks.

**Comment by chenluhong** [comment]
Thanks you very much! I try it again.

**Comment by chenluhong** [comment]
Excuse me! I downloaded the source code again just now, and make it successfully,  the touchscreen can work now. In addition, I want to work it by arm-linux-g++, so I change the Makefile, and also add -lstdc++, but there are many errors when I make it again.

**Comment by yachen** [comment]
Can you post error message here?

**Comment by chenluhong** [comment]
When I used arm-linux-g++ to compiler the project, there were many errors such as
 "../../Config/LCDConf.c:224:41: error：‘g_xres’was not declared in this scope
     GUI_TOUCH_Calibrate(GUI_COORD_X, 0, g_xres, 0, g_xres);
"

**Comment by chenluhong** [comment]
And other several similar errors also occurred in the LCDConf.c.

**Comment by yachen** [comment]
C++ syntax is stricter than C. Please change
`extern  g_xres;`
and other extern variables in LCDConf.c to 
`extern  int g_xres;`

**Comment by chenluhong** [comment]
Ok, thank you!
