### ISSUE TITLE
USB(Device/Host) Sample

### ISSUE THREAD

**Issue by JinZhuXing** [OpenNuvoton/NUC970_Linux_Applications#3]
Hello, I want a USB (device/host) sample code for linux os based application.
But I can't find any project for usb in demos directory.
How can I find sample code for USB?

**Comment by yachen** [comment]
No, we don't have sample application for USB. 
This depends on the USB class you're using. For example, you can use simple and standard APIs open/read/write/close to access USB pen drive. So we don't provide sample code for USB.

**Comment by JinZhuXing** [comment]
And what about Device Sample.
open/read/write you said is Host sample.
I want also USB Device mode sample.
For example, android device can connect to PC as device.
I want samples like this.
NUC972 Non_OS sample contains both USBD and USBH sample.
Please help me.
Thank you.

**Comment by yachen** [comment]
You don't need to write a sample to use USB gadget. Instead, you need to install the kernel objects for the class you want to use. Here's an example for mass storage class
```
$ insmod configfs.ko 
$ insmod libcomposite.ko 
$ insmod g_mass_storage.ko file=/dev/mmcblk0p1 stall=0 removable=1 
```

**Comment by JinZhuXing** [comment]
Excuse me, I have no experience in Linux Kernel Loading.
Please tell me where can I get configfs.ko, libcomposite.ko, g_mass_storage.ko files?
I want to use my device as mass_storage device.
Thank you.

**Comment by JinZhuXing** [comment]
Please help me

**Comment by yachen** [comment]
Please try following config and generate the ko files by re-compile kernel.
```
Device Drivers ---> 
	[*] USB support --->
		<*> USB Gadget Support --->
			USB Peripheral Controller --->
				<*> NUC970/N9H30 USB Device Controller
			<M> USB Gadget Driver
			<M> Mass Storage Gadget
```

**Comment by JinZhuXing** [comment]
Thank you, sir.
But I can't sure, how can I do this config?
Which file contains this config?
I am very sorry to bordering you.
I have no experience in kernel, sorry.
Please help me.
Thank you.

**Comment by yachen** [comment]
You can check following links for some basic knowledge.
https://www.itread01.com/p/160214.html
http://smilejay.com/2011/05/linux-kernel-configuration/

**Comment by JinZhuXing** [comment]
Thank you, Thank you very much.
