### ISSUE TITLE
NUC972测试crypto_demo失败

### ISSUE THREAD

**Issue by 1020165558** [OpenNuvoton/NUC970_Linux_Applications#5]
首先根据BSP手册修改内核

Cryptographic Accelerator設置
要支持Cryptographic Accelerator, 請先勾選打開 Netowrking support裡的PF_KEY socket.
[*] Networking support --->
Networking options --->
<*> PF_KEY sockets
然後再打開 Cryptographic API 裡面的相關設定
Cryptographic API --->
<*> Userspace cryptographic algorithm configuration
[*] Disable run-time self ests
<*> Software async crypto daemon
<*> User-space interface for hash algorithm
<*> User-space interface for symmetric key cipher algorithms
[*] Hardware crypto devices --->
<*> Support for NUC970 Cryptographic Accelerator

按上述修改好内核编译烧录，开机后显示加载驱动失败

NUC970 Crypto initialization failed.
nuc970-crypto: probe of nuc970-crypto failed with error -12

请问是什么原因

**Comment by yachen** [comment]
Hi,

看不出問題. 我測試開了上面選項後正常. 附件是我的 kernel config, 請跟你內核根目錄下的 .config 比對一下.
[linux.zip](https://github.com/OpenNuvoton/NUC970_Linux_Applications/files/5722199/linux.zip)

```
hub 2-0:1.0: USB hub found
hub 2-0:1.0: 2 ports detected
usbcore: registered new interface driver usb-storage
NUC970 Crypto engine enabled.
TCP: cubic registered
NET: Registered protocol family 17
NET: Registered protocol family 15
Freeing unused kernel memory: 4184K
```

Sincerely,

Yi-An Chen

**Comment by 1020165558** [comment]
非常感谢，我测试一下
